// Generated by ReScript, PLEASE EDIT WITH CARE


var _map = {"HALF_ODD":"HALF_ODD","HALF_EVEN":"HALF_EVEN","HALF_UP":"HALF_UP","HALF_DOWN":"HALF_DOWN","HALF_TOWARDS_ZERO":"HALF_TOWARDS_ZERO","HALF_AWAY_FROM_ZERO":"HALF_AWAY_FROM_ZERO","DOWN":"DOWN"};

function roundingModeToJs(param) {
  return param;
}

function roundingModeFromJs(param) {
  return _map[param];
}

export {
  roundingModeToJs ,
  roundingModeFromJs ,
  
}
/* No side effect */
